### PR TITLE
Set up a simple hello world GraphQL-Express_Server

### PR DESCRIPTION
**Pull request by oererenn**
"Set up github repository and a basic "hello world" graphql app based on an express server"

### CODE REVIEW

**Comment by BondarencoM** [comment]
@oererenn  why did you close it?

**Review by BondarencoM — CHANGES_REQUESTED** [review]
@oererenn  can you pleas add node_modules to .gitignore ? It's recommended because node_modeules is huge and adds a lot of clutter to git and slows it down considerably

**Comment by oererenn** [comment]
> @oererenn can you pleas add node_modules to .gitignore ? It's recommended because node_modeules is huge and adds a lot of clutter to git and slows it down considerably

**Comment by oererenn** [comment]
Added gitignore file

**Comment by BondarencoM** [comment]
@oererenn looks like git will continue to track node_moduels because it was committed before the .gitignore. Can you please delete node_modules and commit that change so it's no longer tracked by git?
After that if you run npm install you should have all the dependencies back without them going into git. 
Also let me know if you wanna talk about it ^^

**Comment by oererenn** [comment]
node_modules deleted

**Review by BondarencoM — APPROVED** [review]

**Comment by BondarencoM** [comment]
Awesome!

**Review by larsverp — APPROVED** [review]
Looking good :)

**Pull request merged**
